language: php
php:
  - 7.0
  - 7.1
  - nightly
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
  # Setup display for Selenium
  - google-chrome  --disable-gpu --headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222
before_script:
  # Get and run Selenium
  - wget http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.0.jar -O selenium-server-standalone.jar
  - java -Dwebdriver.chrome.driver=`pwd`/chromedriver -jar selenium-server-standalone.jar > /dev/null 2>&1 &

  # Run composer install
  - composer install
script:
  - vendor/bin/behat -c behatGoutte.yml -s web features/web/exemploGoutte.feature
